=== hamzaanwar9/class_work/validate elements with xml & DTD/paktech_validate_element.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Paktech (employee|clinte)+>
<!ELEMENT employee (name,(email|number)+,password)>
<!ELEMENT clinte (name,email,password)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ENTITY ps SYSTEM "pass1212">
<!ATTLIST email domain CDATA #REQUIRED>

=== hamzaanwar9/class_work/validate elements with xml & DTD/paktech_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Paktech SYSTEM "paktech_validate_element.dtd" [
<!ENTITY pass "pass1122">
]>
<Paktech>

<employee>
<name>hamza</name>
<email domain=""> alexerfro@gmail.com</email>
<number>03223556500</number>
<password>h2345678</password>
</employee>

<clinte>
<name>ali</name>
<email domain="">ali@gmail.com</email>
<password>&pass;</password>
</clinte>

</Paktech>
